# Generated by Django 3.1.4 on 2020-12-27 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresults',
            name='answer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='answer_played', to='games.answer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameresults',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='question_played', to='games.question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gameresults',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_played', to='games.game'),
        ),
    ]
