# Generated by Django 3.1.4 on 2020-12-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20201227_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresults',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
